### ISSUE TITLE
`apt-get update` fails on dashboard PR Jenkins job due to missing language packages within a repository

### ISSUE THREAD

**Issue by callithea** [ceph/ceph-build#1136]
See: https://jenkins.ceph.com/view/all/job/ceph-dashboard-pull-requests/5/consoleFull
``E: Failed to fetch http://mirror.yandex.ru/mirrors/launchpad/ubuntu-toolchain-r/dists/xenial/main/i18n/Translation-en  404  Not Found``
``E: Some index files failed to download. They have been ignored, or old ones used instead.``
The mirror itself still exists, but the sub-directories under ``main`` are no longer available.

Found the related mirror here: https://github.com/ceph/ceph-build/blob/master/scripts/build_utils.sh#L550
Can this mirror be removed or does someone have another fix for this issue?

**Comment by tchaikov** [comment]
@callithea i think the yandex mirror is still usable. what it's missing is but the translation files of package description. and in our case, they are not necessary. so we can continue using it.
