### ISSUE TITLE
Signed-off-by failing when using python3

### ISSUE THREAD

**Issue by djgalloway** [ceph/ceph-build#1770]
Not sure what's going on here but hoping Kefu can take a look.

```
+ /tmp/venv.DVYjyKoxpV/bin/pip install -U pip
Traceback (most recent call last):
  File "/tmp/venv.DVYjyKoxpV/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/tmp/venv.DVYjyKoxpV/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

This started after https://github.com/ceph/ceph-build/pull/1766 got merged

**Comment by djgalloway** [comment]
Maybe we may just now be facing https://pip.pypa.io/en/stable/news/#id1 ?

**Comment by djgalloway** [comment]
Confirmed reverting https://github.com/ceph/ceph-build/pull/1766 (manually) fixes it.  I tried setting the env to use `pip3` instead of `pip` if `pip3` was present but that didn't get us any further.

```
++ command -v /tmp/venv.jAyu84ZReu/bin/pip3
+ '[' /tmp/venv.jAyu84ZReu/bin/pip3 ']'
+ PIP=pip3
+ '[' '' == latest ']'
+ [[ -n '' ]]
+ echo 'Installing pip 10.0.0'
Installing pip 10.0.0
+ /tmp/venv.jAyu84ZReu/bin/pip3 install pip3==10.0.0
Traceback (most recent call last):
  File "/tmp/venv.jAyu84ZReu/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/tmp/venv.jAyu84ZReu/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by dmick** [comment]
Python 3.5.2 is current on Ubuntu 16.04.4 where the failing signed-off tests run, and it does not include support for f-strings.  pip3 apparently now requires at least 3.6.  This is the breaking commit:  https://github.com/pypa/pip/commit/cdcf74fb8eee47ac13f24dc4692c29bc144ea66c

**Comment by tchaikov** [comment]
just wanted to provide a complementary note: ceph-pr-commits are assigned to "small" test nodes . see https://github.com/ceph/ceph-build/blob/ccd3fefb6fa5dc2a4500b5b25e63e5196c30f138/ceph-pr-commits/config/definitions/ceph-pr-commits.yml#L31

with #1766, we will need to use at least bionic or focal for running this job.

**Comment by tchaikov** [comment]
@dmick and thank you for your analysis, Dan!

**Comment by tchaikov** [comment]
@djgalloway can we close this issue, now that #1774 and #1775 were merged and we don't see this failure anymore?
