### ISSUE TITLE
cancel-builds-on-update option is not working as expected

### ISSUE THREAD

**Issue by guits** [ceph/ceph-build#817]
@alfredodeza @djgalloway
the option `cancel-builds-on-update` introduced in 18a1bbc doesn't work at all, I can see jobs gets queued without being canceled when I have to update existing PRs.

I suspect this is because we are using an old version of Jenkins Jobs Builder.
Indeed, this option is available from JJB 2.0 and later.

**Comment by alfredodeza** [comment]
@guits you can use raw/plain XML like in here: 

https://github.com/ceph/ceph-build/blob/master/ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml#L31-L36
